# Generated by Django 5.1.1 on 2024-09-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='ad',
        ),
    ]
