# Generated by Django 5.1.1 on 2024-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
